//@title Rhythm Lab Breaks Explorer @by Claude

// === SAMPLE SOURCE ===
// 757 breaks from rhythm-lab.com, analyzed and organized by bar count.

await samples('https://raw.githubusercontent.com/jhw/strudel-rhythm-lab/main/sounds/strudel.json');

setCps(130/60/4);

// === SLIDERS ===

const breakPick = slider(0, 0, 756, 1);
const patternPick = slider(0, 0, 15, 1);
const gainVal = slider(0.8, 0, 1, 0.1);

// === BREAKS (757 total) ===
// 1-bar: 63, 2-bar: 260, 4-bar: 378, 8-bar: 56

const breaks1 = [
  "20th-century-hot-pants", "abstractions-projections", "average-white-band-big-city", 
  "bernard-purdie-attica-part1", "big-jullien-his-all-star-talk", "buena-vistas-kick-back", 
  "captain-freak-and-the", "cash-mccall-omega-man", "cat-stevens-the-foreigner", 
  "chick-shannon-the-last-exit", "chuck-carbo-can-i-be-your", "chuck-carbo-can-i-be-your-1", 
  "chuck-carbo-can-i-be-your-2", "chuck-carbo-can-i-be-your-3", "dedalus-ct-6-part1", 
  "dedalus-ct-6-part2", "earth-wind-fire-everything-is", "eddie-simpson-big-black-funky", 
  "fabio-frizzi-kalu", "fatback-band-feat-johnny-king", "groove-collective-unknown", 
  "hot-chocolate-you-could-ve", "isaac-hayes-joy-part3", "izakson-artamonov-larin-rpex", 
  "jon-cleary-oh-no-no-no", "kc-and-the-sunshine-band-i-m", "keystones-attack-of-the", 
  "kid-dynamite-uphill-peace-of", "kid-dynamite-uphill-peace-of-1", 
  "kylie-auldist-counting-on-you", "libelous", "lightnin-rod-sport-ver-1", 
  "meters-live-wire-part2", "modern-soul-band-marie-marie", "ohio-players-faith", 
  "piero-piccioni-kintabu", "ralph-carmichael-the-addicts", "ralph-carmichael-the-addicts-1", 
  "ralph-carmichael-the-addicts-3", "ralph-carmichael-the-addicts-5", 
  "ralph-carmichael-the-addicts-6", "ralph-carmichael-the-addicts-7", 
  "ralph-carmichael-the-addicts-8", "roy-porter-sound-machine-1", "secret-chiefs-3-safina", 
  "shotgun-standing-in-need-of", "siegfried-schwab-high-snobiety", "sly-the-family-stone-advice", 
  "sly-the-family-stone-advice-1", "sly-the-family-stone-advice-2", 
  "sly-the-family-stone-advice-3", "smokey-brooks-spin-it-jig", "stanley-clarke-slow-dance", 
  "the-new-mastersounds-all-we", "the-rustix-i-guess-this-is", "the-rustix-i-guess-this-is-1", 
  "third-guitar-baby-dont-cry", "three-dog-night-i-can-hear", "tony-newman-soulthing", 
  "unknown-one-more-thing", "waltel-branco-meu-balanco", "wilson-pickett-land-of-1000", 
  "world-wonders-funky-washing-1"
];

const breaks2 = [
  "2nd-chapter-of-acts-the-devil", "5th-dimension-rainmaker-part1", "african-music-machine-black", 
  "al-kooper-the-landlord", "allen-toussaint-get-out-of-my", "amy-winehouse-you-know-i-m-no", 
  "andre-ceccarelli-gang", "andre-ceccarelli-gang-1", "andre-ceccarelli-gang-2", 
  "andre-ceccarelli-gang-3", "ann-alford-got-to-get-me-a-job", "augusto-alguero-bocaccio-soul", 
  "average-white-band-t-l-c", "b-t-express-do-it-til-you-re", "b-t-express-still-good-still", 
  "bacao-rhythm-steel-band", "bacao-rhythm-steel-band-4", "backyard-heavies-chittlin", 
  "bad-bascomb-black-grass", "bad-medicine-trespasser-part-1", "bad-medicine-trespasser-part-2", 
  "bad-medicine-trespasser-part-3", "barley-bree-save-your-love", "barry-morgan-herbie-flowers-2", 
  "benny-gordon-give-a-damn", "bernard-purdie-bernard-s", "bernard-purdie-bernard-s-1", 
  "bernard-purdie-bernard-s-2", "bernard-purdie-shaft-theme", "bernard-purdie-soul-drums-4", 
  "bernard-purdie-them-changes-1", "bernard-purdie-them-changes-2", 
  "bgm-under-the-flag-of-justice", "big-boss-man-b-o-o-g-a-l-o-o", "big-boss-man-reach-out", 
  "black-heat-zimba-ku", "black-oak-arkansas-hot-and", "blackbyrds-blackbyrds-theme", 
  "blowfly-hold-on-it-s-running", "blowfly-hole-man", "blowfly-my-baby-keeps-farting", 
  "bobby-allen-the-exceptions", "bobby-byrd-hot-pants-bonus", "bobby-byrd-i-know-you-got-soul", 
  "bobby-byrd-the-way-to-get-down", "brother-soul-cookies-part2", 
  "buddy-rich-mercy-mercy-mercy-1", "chanson-did-you-ever", "chick-shannon-the-last-exit-1", 
  "chris-youlden-wake-up", "coke-na-na", "common-saints-lovesong", "craig-peyton-group-snow", 
  "cresa-watson-dead", "cus-the-groove-lewis-let-the", "dan-seepers-group-soielil-de", 
  "david-bowie-join-the-gang", "dee-dee-drums-dee-dee-warwick", "dennis-coffey-son-of-scorpio", 
  "deodato-september-13", "donny-hathaway-magnificent", "duralcha-ghetto-funk", 
  "dyke-and-the-blazers-funky", "dynamic-7-squeezeme-part1", "e-u-knock-him-out-sugar-ray-2", 
  "eddie-bo-hook-and-sling-ver-2", "eddie-lang-souling", "edwin-starr-twenty-five-miles", 
  "enrique-olivarez-y-los", "enrique-olivarez-y-los-1", "explosions-garden-of-four", 
  "fatback-band-lady-groove", "fatback-band-let-me-do-it-to", "fatback-you-gotta-believe", 
  "frank-hatchett-stratus", "frankie-seay-the-soul-riders-2", "freddie-hubbard-south-street", 
  "funk-brothers-i-can-t-get", "funkadelic-good-old-music", "garnet-mimms-stop-check", 
  "gasolin-solfanger", "goblin-snip-snap", "grass-roots-the-you-and-love", 
  "harlem-underground-band-feat", "harlem-underground-band-feat-1", "harvey-mandel-baby-batter", 
  "harvey-the-phenomenals-soul", "honeydrippers-impeach-the", "honeydrippers-impeach-the-1", 
  "honeydrippers-impeach-the-2", "hot-chocolate-disco-queen", "idris-muhammad-express", 
  "idris-muhammad-gccg-blues", "idris-muhammad-tasty-cakes", "ike-tina-turner-cussin-cryin", 
  "isaac-hayes-breakthrough", "isaac-hayes-joy-part1", "isaac-hayes-joy-part2", 
  "james-brown-dead-on-it-pt2", "james-brown-say-it-loud-i-m", "james-taylor-and-the-original", 
  "jay-mitchell-funky-fever-part3", "jesse-and-erson-mighty-mighty", 
  "joe-tex-papa-was-too-ver-2-1", "johnny-hammond-shifting-gears", "johnny-hammond-soul-talk-70", 
  "kashmere-stage-band-scorpio", "kc-and-the-sunshine-band", "keith-mansfield-gladiator", 
  "keith-mansfield-gladiator-1", "keith-mansfield-young-scene", "kenny-dope-can-u-handle-it", 
  "kenny-salmon-get-up-and-go", "khruangbin-the-number-4", "klaus-weiss-research-part1", 
  "klaus-weiss-research-part2", "kool-the-gang-12345678-part2", "kool-the-gang-chocolate", 
  "kool-the-gang-give-it-up-part", "kylie-auldist-nothin-else-to", "led-zeppelin-crunge", 
  "lee-dorsey-get-out-of-my-life", "lee-dorsey-i-can-t-get-away", "les-mccann-north-carolina", 
  "lettuce-bowler", "little-beaver-i-like-the-way", "lonnie-smith-spinnin-wheel", 
  "lonnie-smith-spinnin-wheel-1", "lonnie-smith-spinnin-wheel-2", "lorraine-jackson-take-it", 
  "lou-courtney-hey-joyce-part2", "lou-donaldson-turtle-walk", "lou-donaldson-turtle-walk-1", 
  "luis-enriquez-bacalov", "lyn-collins-wheel-of-life", "magic-disco-machine-scratchin", 
  "magic-disco-machine-scratchin-1", "manfred-krug-wenn-der-urlaub", 
  "manzel-evil-wicked-mean-and", "manzel-jump-street", "manzel-jump-street-1", 
  "manzel-space-funk-dopebrother-1", "manzel-the-party-dopebrother", 
  "marva-whitney-things-got-to", "marvin-holmes-ooh-ooh-the", "maskman-the-agents-one-eye", 
  "matthew-larkin-cassell-in-my", "melvin-bliss-synthetic", "melvin-jackson-1969-funky", 
  "melvin-van-peebles-sweetback", "mfsb-get-down-with-the-philly", "mike-moran-the-pick-up-part2", 
  "monkees-mary-mary", "mother-s-finest-funky-mountain", "mountain-long-red", 
  "nat-adderley-new-orleans", "new-birth-got-to-get-a-knutt", "new-birth-keep-on-do-in-it", 
  "nicole-willis-keep-reachin-up", "norman-connors-kingston-part2", "nostalgia-77-changes", 
  "odetta-hit-or-miss-cd", "ohio-players-funky-worm", "p-f-flyer-rocks-off-part2", 
  "paul-simon-fifty-ways-to", "pavel-sysoyev-zabludilsya-1", "peter-thomas-sound-orch-the", 
  "pointer-sisters-yes-we-can", "pointer-sisters-yes-we-can-1", "ralph-carmichael-the-addicts-2", 
  "ralph-carmichael-the-addicts-4", "ramsey-lewis-back-in-the-u-s", 
  "ramsey-lewis-the-mighty-quinn", "rare-earth-get-ready-part3", "rare-earth-i-just-want-to", 
  "ray-cameron-alan-parker-alan", "reverend-cleatus-the-slip", "rim-shots-dance-girl", 
  "rolling-stones-honky-tonk", "ronald-stein-go-home-pigs", "ronnie-keaton-going-down-for", 
  "rotary-connection-life-could", "rufus-thomas-do-the-funky-2", "ruth-copeland-gimme-shelter", 
  "ruth-copeland-suburban-family", "s-o-u-l-get-ready", "sagaflex-rudy-tee-first-time", 
  "samba-soul-chove-chuva-part1", "sharon-jones-the-dap-kings", "shotgun-good-bad-and-funky", 
  "shotgun-wanna-have-a-good-time", "skull-snaps-its-a-new-day-ver", 
  "skull-snaps-its-a-new-day-ver-1", "sl-troopers-movement", "small-faces-rollin-over", 
  "solomon-burke-get-out-of-my", "soul-stoppers-band-boilin", "spanky-wilson-message-to", 
  "spanky-wilson-sunshine-of-1", "spittin-image-jbs-latin", "steve-colt-dynamite1", 
  "steve-miller-band-take-the-1", "stone-roses-fools-gold", "sugar-billy-garner-i-got-some", 
  "sugar-ray-fly", "supreme-dj-nyborn-versatile", "supreme-dj-nyborn-versatile-1", 
  "t-elerth-beatin-it", "tag-team-triangle-blissom", "the-bamboos-cut-me-down-feat", 
  "the-bamboos-funky-buttercup-1", "the-bamboos-funky-buttercup-2", 
  "the-bamboos-i-got-burned-feat", "the-bamboos-medicine-man-feat", "the-bamboos-midnight-feat", 
  "the-bamboos-what-i-know-feat", "the-cates-gang-one-woman-man", "the-crusaders-lilies-of-the", 
  "the-doobie-brothers-here-to", "the-doobie-brothers-here-to-1", "the-invaders-it-s-your-thing", 
  "the-jaggerz-memoirs-of-the", "the-m-fault-of-love", "the-maytals-who-knows-better", 
  "the-monkees-mary-mary-cd", "the-new-apocalypse-get-outta", "the-new-mastersounds", 
  "the-new-mastersounds-baby", "the-new-mastersounds-hole-in", "the-new-mastersounds-looking", 
  "the-new-mastersounds-miracles", "the-new-mastersounds-miracles-1", 
  "the-new-mastersounds-soulshine", "the-new-mastersounds-the-2", "the-olympics-i-ll-do-a-little", 
  "the-spinners-all-that", "the-sweet-vandals-papa-s-got", "the-victors-magnificent", 
  "thunder-lightning-bumpin-bus", "timebox-save-your-love", "timmy-thomas-sexy-woman", 
  "titanic-something-on-my-mind", "tribe-koke-extended-edit", "turner-brothers-sweetest", 
  "ultrafunk-buffalo-soldier", "ultrafunk-sweet-f-a", "ultrafunk-who-is-he-and-what", 
  "uncle-louie-badd-motor-folk-1", "uncle-louie-i-like-funky-1", "vampisoul-solar-heat", 
  "vecchio-nsambei", "vern-blair-debate-super-funk-1", "victor-chizhova-boris-baykov", 
  "william-s-fischer-gurea-da", "willie-bobo-funky-sneakers", "willis-gator-tail-jackson-ain", 
  "wilson-pickett-get-me-back-on", "wilton-felder-the-cycles-of", "yellow-sunshine-yellow-1", 
  "zdzislawa-sosnicka-ludzie"
];

const breaks4 = [
  "4th-coming-you-don-t-stand-a", "5stairsteps-don-t-change-your", "5th-dimension-rainmaker-cd", 
  "aerosmith-walk-this-way", "afrique-house-of-rising-funk", "afrique-house-of-rising-funk-1", 
  "akira-ishikawa-his-count", "al-jarreau-kissing-my-love", "al-jarreau-kissing-my-love-cd", 
  "al-kooper-soul-hoedown-part1", "al-kooper-soul-hoedown-part2", "alatac-funky-in-jamaica", 
  "alphonse-mouzon-you-don-t", "alphonse-mouzon-you-don-t-1", "alvin-cash-keep-on-dancing", 
  "apple-the-three-oranges-curse", "augustine-ramirez-pack-my-bag", 
  "average-white-band-school-boy", "b-w-souls-marvin-s-groove", "baader-meinhof-it-s-a-moral", 
  "babe-ruth-keep-your-distance", "bacao-rhythm-steel-band-1", "bacao-rhythm-steel-band-2", 
  "bacao-rhythm-steel-band-bacao", "bacao-rhythm-steel-band-dog", "bah-samba-let-the-drums-speak", 
  "banbarra-shack-up", "basement-khemists-everybody", "bernard-purdie-ad-lib-part1", 
  "bernard-purdie-ad-lib-part2", "bernard-purdie-ad-lib-part3", "bernard-purdie-alexander-s", 
  "bernard-purdie-alexander-s-1", "bernard-purdie-butterfingers", "bernard-purdie-funky-donkey-1", 
  "bernard-purdie-funky-donkey-2", "bernard-purdie-hap-nin-part1", "bernard-purdie-hap-nin-part2", 
  "bernard-purdie-heavy-soul-2", "bernard-purdie-heavy-soul-3", "bernard-purdie-heavy-soul-4", 
  "bernard-purdie-on-the", "bernard-purdie-soul-drums-1", "bernard-purdie-soul-drums-2", 
  "bernard-purdie-soul-drums-3", "bernard-purdie-them-changes", "bernard-purdie-theme-from-2", 
  "bernard-purdie-theme-from-3", "big-boss-man-big-boss-buddha", "big-boss-man-humanize-part2", 
  "big-boss-man-kelvin-stardust", "big-boss-man-sea-groove", "bill-withers-kissing-my-love", 
  "bill-withers-kissing-my-love-1", "billy-cobham-light-at-the-end", "billy-squier-big-beat", 
  "birtha-judgement-day-part-1-cd", "birtha-judgement-day-part-2-cd", 
  "birtha-judgement-day-part1", "birtha-judgement-day-part2", "black-joe-lewis-the", 
  "black-oak-arkansas-i-could", "black-pearl-cold-sweat-part2", "black-pearl-cold-sweat-part3", 
  "blowfly-sesame-street-theme", "blowfly-sesame-street-theme-1", 
  "blues-magoos-can-t-get-enough-1", "bobby-hutcherson-rain-every", 
  "bram-tchaikovsky-whiskey-and", "bram-tchaikovsky-whiskey-and-1", "brother-soul-cookies-part1", 
  "buari-ku-ka-maria-part1", "buari-ku-ka-maria-part2", "buddy-rich-big-mama-cass", 
  "caldonia-barbados-stew", "carleen-and-the-groovers", "carleen-and-the-groovers-the", 
  "cecil-holmes-i-m-gonna-love", "charlie-whitehead-let-s-do-it", "chi-lites-are-you-my-woman", 
  "coke-escovedo-i-wouldn-t", "coke-escovedo-i-wouldn-t-1", "cold-blood-kissing-my-love", 
  "cold-blood-shop-talk", "commodores-assembly-line-part1", "commodores-assembly-line-part2", 
  "communicators-black", "curtis-mayfield-freak-freak", "dakari-eltsuhg-ibal-lasiti", 
  "dark-jazzor-bel-air-project", "dennis-coffey-ride-sally-ride", 
  "dennis-coffey-ride-sally-ride-1", "dennis-coffey-scorpio-cd", "dennis-coffey-scorpio-part1", 
  "dennis-coffey-scorpio-part2", "dennis-coffey-scorpio-part3", "dennis-coffey-scorpio-part4", 
  "detroit-emeralds-you-re", "dexter-wansel-theme-from-the", "drums-of-death-bonus-beat-2", 
  "duke-williams-chinese-chicken", "dyke-and-the-blazers-bring-it", "e-u-knock-him-out-sugar-ray", 
  "e-u-knock-him-out-sugar-ray-1", "earth-wind-fire-happy-feelin", "ebony-rhythm-band-soul-heart", 
  "eddie-bo-hook-and-sling-ver-1", "eddie-bo-hook-and-sling-ver-1-1", 
  "ernie-the-top-notes-dap-walk", "esther-williams-last-night", "etta-james-out-on-the-street", 
  "fat-larry-s-band-down-on-the", "fat-larry-s-band-down-on-the-1", "fausto-papetti-love-s-theme", 
  "fausto-papetti-tutta-n-ata", "fbi-fbi", "fearless-incognito", "finished-touch-mighty-good", 
  "finished-touch-new-frontiers", "frankie-seay-the-soul-riders", 
  "frankie-seay-the-soul-riders-1", "free-mr-big-ver-1", "funk-inc-kool-is-back", 
  "funkadelic-good-old-music-4", "funkadelic-i-ll-bet-you", "funkadelic-you-ll-like-it-too", 
  "funky-constellation-street", "funky-constellation-street-1", "funky-constellation-street-2", 
  "fuzzy-haskins-fuz-the-boog", "galactic-force-band-space-dust", "gaz-sing-sing", 
  "gianni-ferrio-la-gabbia-alain", "giuliano-sorgini-wondering-man", "grady-tate-be-black-baby", 
  "h-p-b-mix-light-my-fire", "hand-made-passport", "harmony-cats-cats-theme-kon", 
  "harva-hodge-the-moodysec-let", "harvey-mandel-wade-in-the", "headhunters-god-made-me-funky", 
  "headhunters-god-made-me-funky-1", "headhunters-god-made-me-funky-2", 
  "herman-kelly-life-dance-to", "herman-kelly-life-dance-to-1", "hermann-thieme-dirty-drugs", 
  "hilton-felton-be-bop-boogie", "hilton-felton-be-bop-boogie-1", "hogin-machine-les-baxter", 
  "hot-chocolate-funky-rock-n", "ian-langley-chicano-chaser", "idris-muhammad-dont-knock-my", 
  "isaac-hayes-run-fay-run", "islandman-rest-in-space", "ivor-raymonde-orchestra-it-s", 
  "j-j-johnson-willie-chase-part1", "j-j-johnson-willie-chase-part2", 
  "jack-arel-psychedelic-portrait", "james-brown-cold-sweat-ver-1", 
  "james-brown-cold-sweat-ver-2", "james-brown-funky-president", "james-brown-funky-president-1", 
  "james-brown-funky-president-2", "james-brown-give-it-up-or", "james-brown-hustle-dead-on-it", 
  "james-brown-soul-pride-part3", "james-brown-soul-pride-part4", "james-clarke-the-heavies", 
  "janet-dubois-queen-of-the", "jay-mitchell-funky-fever-part2", "jay-mitchell-funky-fever-part4", 
  "jayson-lindh-your-own-house", "jeremy-steig-alias", "jimi-hendrix-little-miss", 
  "jimi-hendrix-little-miss-1", "jimmy-castor-bunch-it-s-just", "jimmy-mc-griff-the-worm", 
  "jingo-fever", "joe-bataan-when-you-re-down", "joe-farrell-great-gorge", 
  "john-davis-the-monster", "john-davis-the-monster-1", "john-mclaughlin-planetary", 
  "johnny-hammond-soul-talk-70-1", "johnny-holiday-tormented", "johnny-jenkins-i-walk-on", 
  "johnny-jenkins-i-walk-on-2", "johnny-pate-shaft-in-africa", "johnny-pearson-product", 
  "jon-cleary-is-it-any-wonder", "kashmere-stage-band-scorpio-1", "kay-gees-i-believe-in-music", 
  "kc-and-the-sunshine-band-let", "kc-and-the-sunshine-band-let-1", 
  "kc-and-the-sunshine-band-rock", "keith-mansfield-powerhouse-pop", 
  "kenny-smith-go-for-yourself", "kool-the-gang-fresh", "kool-the-gang-give-it-up-part-1", 
  "kool-the-gang-nt-ver-1", "kool-the-gang-nt-ver-2", "korn-the-dust-brothers-kick", 
  "l-a-bare-faxx-super-cool", "la-pregunta-shangi-la", "lafayette-afro-rock-band-conga", 
  "lamont-dozier-take-off-your", "lightnin-rod-sport-ver-2", "liquid-liquid-cavern", 
  "lou-donaldson-ode-to-billy-joe", "luis-enriqoez-baclov", "madjafala-omonyi", 
  "magic-touch-you-are-what-you", "magnum-music-makes-us-do-it", "manzel-it-s-over-now", 
  "manzel-space-funk-dopebrother-2", "marva-whitney-unwind-yourself", 
  "mary-jane-hooper-don-t-change", "melvin-sparks-get-ya-some", "melvin-van-peebles-save-the", 
  "meters-here-comes-the-meter", "meters-just-kissed-my-baby", "meters-live-wire-part1", 
  "meters-look-ka-py-py", "meters-the-hand-clapping-song", "meters-the-hand-clapping-song-1", 
  "miami-chicken-yellow-part1", "miami-chicken-yellow-part2", "michael-viner-s-incredible", 
  "michael-viner-s-incredible-1", "michael-viner-s-incredible-3", "michael-viner-s-incredible-4", 
  "michael-viner-s-incredible-5", "michael-viner-s-incredible-6", "michael-viner-s-incredible-8", 
  "michael-viner-s-incredible-9", "mike-moran-the-pick-up-part1", "mohawks-mony-mony", 
  "monk-higgins-one-man-band", "monk-higgins-one-man-band-1", "naomi-shelton-make-the-road", 
  "nicole-willis-keep-reachin-up-1", "nicole-willis-the-soul", "norman-connors-disco-land", 
  "norman-connors-kingston-part1", "odetta-hit-or-miss", "oneness-of-juju-too-poo", 
  "orange-krush-action-part2", "orange-krush-action-part3", "orange-krush-action-part4", 
  "p-f-flyer-rocks-off-part1", "parliament-come-in-out-of-the", "pattijo-make-me-believe-in-you", 
  "pavel-sysoyev-gostiny-dvor", "pavel-sysoyev-zabludilsya", "paz-laying-eggs", 
  "peter-herbolzheimer-butterfly", "piotr-figie-5x5-55", "pleasure-bouncy-lady", 
  "pomogite-izvinite-part1", "pomogite-izvinite-part2", "pomogite-izvinite-part3", 
  "pomogite-izvinite-part4", "pomogite-ubijcy-v-belyx", "ramsey-lewis-back-in-the-u-s-1", 
  "ramsey-lewis-back-in-the-u-s-2", "ramsey-lewis-back-in-the-u-s-3", "rhon-silva-get-it-right", 
  "rhythm-makers-monterey", "rickey-calloway-tell-me", "roger-glenn-overtime", 
  "roy-ayers-ubiquity-the-boogie", "roy-clark-magnificent", "roy-porter-sound-machine", 
  "roy-porter-sound-machine-2", "rufus-thomas-do-the-funky-1", "rusty-bryant-fire-eater-part2", 
  "rusty-bryant-fire-eater-part3", "rusty-bryant-fire-eater-part4", 
  "rusty-bryant-fire-eater-part6", "s-o-u-l-burning-spear-part1", "s-o-u-l-burning-spear-part2", 
  "sam-the-soul-machine-gun", "sarolta-zalatnay-hadd-mondjam", "shawn-lee-s-ping-pong", 
  "shawn-lee-s-ping-pong-1", "shawn-lee-s-ping-pong-3", "simtec-and-wylie-bootleggin", 
  "sir-joe-quarterman-free-soul", "six-feet-under-chocolate-sugar", "sly-the-family-stone-sing-a", 
  "solomon-burke-get-out-of-my-1", "soul-president-got-to-have-it", "soul-searchers-1993", 
  "soul-searchers-ashley-s", "soul-searchers-ashley-s-1", "soul-senders-soul-brothers", 
  "soul-tornados-crazy-legs", "soulistics-jones-n", "sound-experience-boogie-woogie", 
  "sound-experience-devil-with-a", "sounds-pop-drugpop", "spanky-wilson-kissing-my-love", 
  "spanky-wilson-sunshine-of", "squallor-d-annunziata-part1", "squallor-d-annunziata-part2", 
  "stanley-turrentine-sister", "stanley-turrentine-sister-1", "steve-miller-band-take-the", 
  "stevie-wonder-passo-le-mie-1", "survival-annette-peacock", "syl-johnson-different-strokes", 
  "syl-johnson-ode-to-soul-man", "syl-johnson-right-on", "t-connection-groove-to-get", 
  "the-bamboos-amen-brother-part1", "the-bamboos-can-t-help-myself", 
  "the-bamboos-funky-buttercup", "the-bamboos-one-man-entourage", "the-bamboos-soul-clappin", 
  "the-blenders-nothin-but-a", "the-blenders-nothin-but-a-1", "the-jim-entley-sound-charlies", 
  "the-johnny-frigo-sextet", "the-mighty-dogcatchers-it-s", "the-mighty-tom-cats-soul", 
  "the-new-mastersounds-better", "the-new-mastersounds-butter", "the-new-mastersounds-butter-1", 
  "the-new-mastersounds-dusty", "the-new-mastersounds-dusty-1", "the-new-mastersounds-funky", 
  "the-new-mastersounds-funky-1", "the-new-mastersounds-funky-2", "the-new-mastersounds-funky-3", 
  "the-new-mastersounds-give-me", "the-new-mastersounds-give-me-1", 
  "the-new-mastersounds-nervous", "the-new-mastersounds-nervous-1", 
  "the-new-mastersounds-nervous-2", "the-new-mastersounds-nothing", "the-new-mastersounds-pure", 
  "the-new-mastersounds-the", "the-new-mastersounds-the-1", "the-olympics-i-ll-do-a-little-1", 
  "the-playboys-bumpin-bus-stop", "the-poets-fun-buggy", "the-producers-library", 
  "the-soul-seven-the-cissy-s", "thin-lizzy-johnny-the-fox", "third-guitar-baby-don-t-cry", 
  "tom-scott-the-l-a-express", "tony-avlon-sexy-coffee-pot-1", "tony-cook-the-ga-s-funky", 
  "tony-cook-the-ga-s-slip-the", "tony-cook-the-ga-s-time-out-1", "tony-cook-the-ga-s-time-out-2", 
  "tower-of-power-ebony-jam-part1", "tower-of-power-ebony-jam-part2", 
  "tower-of-power-squib-cakes", "tower-of-power-squib-cakes-1", "tyrone-harris-ain-t-that-fun", 
  "ultrafunk-kung-fu-man", "uncle-louie-badd-motor-folk", "uncle-louie-i-like-funky", 
  "unknown-unknown1", "upp-give-it-to-you", "via-rapsodia-parafraz-na-temu", 
  "via-rapsodiya-ya-na-tansy", "vibrettes-humpty-dump", "village-crusaders-akiwawa", 
  "we-the-people-breakdown-part1", "wilbur-bascomb-and-zodiact", "wild-magnolias-soul-soul-soul", 
  "wild-sugar-bring-it-here", "willie-bobo-always-there", "world-wonders-funky-washing", 
  "yellow-sunshine-yellow", "z-z-hill-i-think-i-d-do-it"
];

const breaks8 = [
  "101-strings-high-on-the", "7eleven-dance-the-slurp", "all-the-people-cramp-your", 
  "arthur-monday-what-goes", "baby-huey-the-babysitters", "bacao-rhythm-steel-band-3", 
  "barry-morgan-herbie-flowers-1", "bernard-purdie-caravan", "bernard-purdie-heavy-soul", 
  "bernard-purdie-new-orleans", "big-boss-man-fever-special", "blues-magoos-can-t-get-enough", 
  "bobby-cook-on-the-way", "bobby-williams-boogaloo-mardi", "boobie-knight-the-universal", 
  "brothers-johnson-ain-t-we", "cesar-mariano-and-cia", "chanson-dont-hold-back", 
  "chuck-colbert-oof-do-anything", "dyke-the-blazers-let-a-woman", "fans-roly-poly-micky-lolich", 
  "gintarine-pora-saulelydis", "harold-malbern-i-want-you-back", "hot-chocolate-could-have-been", 
  "inclines-the-atlanta-boogaloo", "james-brown-funky-drummer-ver", 
  "james-brown-funky-drummer-ver-1", "james-brown-soul-pride-vinyl", "john-davis-i-can-t-stop", 
  "little-buck-soul-brother-soul", "little-buck-you-got-too-pt-2", 
  "lucy-hawkins-gotta-get-out-of", "manzel-just-for-you", "manzel-midnight-theme", 
  "manzel-space-funk-dopebrother", "melvin-van-peebles-come-on", "michael-viner-s-incredible-2", 
  "mickey-the-soul-generation", "nu-people-id-be-nowhere", "phil-ranelin-vibes-from-the", 
  "pucho-got-myself-a-good-man", "riz-ortolani-secret-meeting", "roy-head-shes-about-a-mover", 
  "salt-hung-up", "sapo-beenhad-part1-2", "shawn-lee-s-ping-pong-2", "shawn-lee-s-ping-pong-4", 
  "south-bronx-the-bottom-line", "southside-movement-save-the-1", "spinners-one-one-two-two", 
  "steve-colt-dynamite2", "steve-grossman-zulu-stomp", "the-bamboos-the-side-stepper", 
  "the-crusaders-free-as-the-wind", "tony-avlon-sexy-coffee-pot", "vern-blair-debate-super-funk"
];

const allBreaks = [...breaks1, ...breaks2, ...breaks4, ...breaks8];

const barCounts = [
  ...Array(63).fill(1),  // 63 x 1-bar
  ...Array(260).fill(2),  // 260 x 2-bar
  ...Array(378).fill(4),  // 378 x 4-bar
  ...Array(56).fill(8),  // 56 x 8-bar
];

const sliceCounts = barCounts.map(b => b * 8);

// === PATTERNS ===

const patterns1 = [
  "{0 2 4 6}%8", "{0 3 4 6}%8", "{0 2 5 6}%8", "{1 2 4 6}%8",
  "{0 2 4 7}%8", "{0 3 5 6}%8", "{0 2 3 6}%8", "{1 2 5 6}%8",
  "{0 1 4 6}%8", "{0 2 4 5}%8", "{0 3 4 7}%8", "{1 3 5 7}%8",
  "{0 1 2 4}%8", "{4 5 6 7}%8", "{0 2 4 6}%8", "{0 4 5 6}%8",
];

const patterns2 = [
  "{0 2 4 6 8 10 12 14}%8", "{0 3 4 6 8 11 12 14}%8",
  "{0 2 5 6 8 10 13 14}%8", "{1 2 4 6 9 10 12 14}%8",
  "{0 2 4 7 8 10 12 15}%8", "{0 3 5 6 8 11 13 14}%8",
  "{0 2 3 6 8 10 11 14}%8", "{1 2 5 6 9 10 13 14}%8",
  "{0 1 4 6 8 9 12 14}%8", "{0 2 4 5 8 10 12 13}%8",
  "{0 3 4 7 8 11 12 15}%8", "{1 3 5 7 9 11 13 15}%8",
  "{0 1 2 4 8 9 10 12}%8", "{4 5 6 7 12 13 14 15}%8",
  "{0 2 4 6 8 10 12 14}%8", "{0 4 5 6 8 12 13 14}%8",
];

const patterns4 = [
  "{0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30}%8",
  "{0 3 4 6 8 11 12 14 16 19 20 22 24 27 28 30}%8",
  "{0 2 5 6 8 10 13 14 16 18 21 22 24 26 29 30}%8",
  "{1 2 4 6 9 10 12 14 17 18 20 22 25 26 28 30}%8",
  "{0 2 4 7 8 10 12 15 16 18 20 23 24 26 28 31}%8",
  "{0 3 5 6 8 11 13 14 16 19 21 22 24 27 29 30}%8",
  "{0 2 3 6 8 10 11 14 16 18 19 22 24 26 27 30}%8",
  "{1 2 5 6 9 10 13 14 17 18 21 22 25 26 29 30}%8",
  "{0 1 4 6 8 9 12 14 16 17 20 22 24 25 28 30}%8",
  "{0 2 4 5 8 10 12 13 16 18 20 21 24 26 28 29}%8",
  "{0 3 4 7 8 11 12 15 16 19 20 23 24 27 28 31}%8",
  "{1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31}%8",
  "{0 1 2 4 8 9 10 12 16 17 18 20 24 25 26 28}%8",
  "{4 5 6 7 12 13 14 15 20 21 22 23 28 29 30 31}%8",
  "{0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30}%8",
  "{0 4 5 6 8 12 13 14 16 20 21 22 24 28 29 30}%8",
];

const patterns8 = [
  "{0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62}%8",
  "{0 3 4 6 8 11 12 14 16 19 20 22 24 27 28 30 32 35 36 38 40 43 44 46 48 51 52 54 56 59 60 62}%8",
  "{0 2 5 6 8 10 13 14 16 18 21 22 24 26 29 30 32 34 37 38 40 42 45 46 48 50 53 54 56 58 61 62}%8",
  "{1 2 4 6 9 10 12 14 17 18 20 22 25 26 28 30 33 34 36 38 41 42 44 46 49 50 52 54 57 58 60 62}%8",
  "{0 2 4 7 8 10 12 15 16 18 20 23 24 26 28 31 32 34 36 39 40 42 44 47 48 50 52 55 56 58 60 63}%8",
  "{0 3 5 6 8 11 13 14 16 19 21 22 24 27 29 30 32 35 37 38 40 43 45 46 48 51 53 54 56 59 61 62}%8",
  "{0 2 3 6 8 10 11 14 16 18 19 22 24 26 27 30 32 34 35 38 40 42 43 46 48 50 51 54 56 58 59 62}%8",
  "{1 2 5 6 9 10 13 14 17 18 21 22 25 26 29 30 33 34 37 38 41 42 45 46 49 50 53 54 57 58 61 62}%8",
  "{0 1 4 6 8 9 12 14 16 17 20 22 24 25 28 30 32 33 36 38 40 41 44 46 48 49 52 54 56 57 60 62}%8",
  "{0 2 4 5 8 10 12 13 16 18 20 21 24 26 28 29 32 34 36 37 40 42 44 45 48 50 52 53 56 58 60 61}%8",
  "{0 3 4 7 8 11 12 15 16 19 20 23 24 27 28 31 32 35 36 39 40 43 44 47 48 51 52 55 56 59 60 63}%8",
  "{1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63}%8",
  "{0 1 2 4 8 9 10 12 16 17 18 20 24 25 26 28 32 33 34 36 40 41 42 44 48 49 50 52 56 57 58 60}%8",
  "{4 5 6 7 12 13 14 15 20 21 22 23 28 29 30 31 36 37 38 39 44 45 46 47 52 53 54 55 60 61 62 63}%8",
  "{0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62}%8",
  "{0 4 5 6 8 12 13 14 16 20 21 22 24 28 29 30 32 36 37 38 40 44 45 46 48 52 53 54 56 60 61 62}%8",
];

const allPatterns = [...patterns1, ...patterns2, ...patterns4, ...patterns8];
const patternOffsets = barCounts.map(b => b === 1 ? 0 : b === 2 ? 16 : b === 4 ? 32 : 48);

// === OUTPUT ===

note(36).sound(pick(breakPick, allBreaks))
  .loopAt(pick(breakPick, barCounts))
  .slice(pick(breakPick, sliceCounts), pick(patternPick.add(pick(breakPick, patternOffsets)), allPatterns))
  .gain(gainVal);
